apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-be
  namespace: backend
  labels:
    app: employee-be
spec:
  selector:
    matchLabels:
      app: employee-be
  template:
    metadata:
      labels:
        app: employee-be
    spec:
      containers:
        - name: employee-be
          image: devops/employee-be:1.0.9
          imagePullPolicy: IfNotPresent
          ports:
            - name: instance-port
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: employee-be-config
